#!/usr/bin/env python3
"""Generate panel-nubia-nx669j-seq.h from the stock NX669J dtbo.

The REDMAGIC 6 ships several 1080x2400 AMOLED panels (Novatek NT37701 and
NT37800A, each in two revisions). Their init sequences, timings and DSC
settings only exist in Nubia's downstream devicetree overlay, so this turns
that data into C tables for the mainline panel driver instead of copying
hundreds of bytes by hand.

usage: gen-panel-seq.py <decompiled dtbo .dts> <out.h>
  (dtc -I dtb -O dts dtbo-entry.dtb; the "Lahaina MTP" entry, board-id 0x10008)
"""
import re
import sys

VARIANTS = [
    # (C name, downstream node label)
    ("nt37701", "dsi_nubia_nt37701_amoled_cmd_cphy"),
    ("nt37701_b0", "dsi_nubia_nt37701_amoled_cmd_cphy_b0"),
    ("nt37800a", "dsi_nubia_nt37800a_amoled_cmd_cphy"),
    ("nt37800a_b6", "dsi_nubia_nt37800a_amoled_cmd_cphy_b6"),
]


def block(text, start):
    i = text.index("{", start)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
    raise ValueError("unbalanced")


def prop_bytes(blk, name):
    # dtc prints byte strings whose length is a multiple of 4 as <u32> cells.
    m = re.search(r"\n\s*" + re.escape(name) + r" = (\[[0-9a-f ]*\]|<[^>]*>);", blk)
    if not m:
        return None
    v = m.group(1)
    if v.startswith("["):
        return [int(x, 16) for x in v[1:-1].split()]
    return [b for x in v[1:-1].split() for b in int(x, 0).to_bytes(4, "big")]


def prop_u32(blk, name):
    m = re.search(r"\n\s*" + re.escape(name) + r" = <([^>]*)>;", blk)
    if not m:
        return None
    return [int(x, 0) for x in m.group(1).split()]


def parse_cmds(raw):
    """Qualcomm dsi cmd blob: type, last, vc, ack, wait_ms, len_hi, len_lo, payload."""
    cmds, i = [], 0
    while raw and i < len(raw):
        dtype, _last, _vc, _ack, wait = raw[i:i + 5]
        n = (raw[i + 5] << 8) | raw[i + 6]
        payload = raw[i + 7:i + 7 + n]
        if len(payload) != n:
            raise ValueError("truncated command blob")
        cmds.append((dtype, wait, payload))
        i += 7 + n
    return cmds


def c_cmds(name, cmds):
    out = [f"static const struct nx669j_cmd {name}[] = {{"]
    for dtype, wait, payload in cmds:
        data = ", ".join(f"0x{b:02x}" for b in payload)
        out.append(f"\t{{ 0x{dtype:02x}, {wait}, {len(payload)}, (const u8[]){{ {data} }} }},")
    out.append("};")
    return "\n".join(out)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src).read()
    out = [
        "/* SPDX-License-Identifier: GPL-2.0-only */",
        "/* Generated by gen-panel-seq.py from the stock NX669J-UN dtbo. Do not edit. */",
        "",
    ]
    variants = []
    for cname, label in VARIANTS:
        pos = text.index(f"{label}: ")
        pnode = block(text, pos)
        modes = []
        for tm in re.finditer(r"timing@(\d+) \{", pnode):
            t = block(pnode, tm.start())
            rate = prop_u32(t, "qcom,mdss-dsi-panel-framerate")[0]
            mode = dict(
                rate=rate,
                w=prop_u32(t, "qcom,mdss-dsi-panel-width")[0],
                h=prop_u32(t, "qcom,mdss-dsi-panel-height")[0],
                hfp=prop_u32(t, "qcom,mdss-dsi-h-front-porch")[0],
                hbp=prop_u32(t, "qcom,mdss-dsi-h-back-porch")[0],
                hpw=prop_u32(t, "qcom,mdss-dsi-h-pulse-width")[0],
                vfp=prop_u32(t, "qcom,mdss-dsi-v-front-porch")[0],
                vbp=prop_u32(t, "qcom,mdss-dsi-v-back-porch")[0],
                vpw=prop_u32(t, "qcom,mdss-dsi-v-pulse-width")[0],
                slice_h=prop_u32(t, "qcom,mdss-dsc-slice-height")[0],
                slice_w=prop_u32(t, "qcom,mdss-dsc-slice-width")[0],
                bpc=prop_u32(t, "qcom,mdss-dsc-bit-per-component")[0],
                bpp=prop_u32(t, "qcom,mdss-dsc-bit-per-pixel")[0],
                spp=(prop_u32(t, "qcom,mdss-dsc-slice-per-pkt") or [1])[0],
                on=parse_cmds(prop_bytes(t, "qcom,mdss-dsi-on-command")),
                switch=parse_cmds(prop_bytes(t, "qcom,mdss-dsi-timing-switch-command") or []),
                off=parse_cmds(prop_bytes(t, "qcom,mdss-dsi-off-command")),
            )
            modes.append(mode)
        modes.sort(key=lambda m: -m["rate"])
        # Each timing carries its own full init sequence (the rate-specific
        # register tables differ, not just the final rate select).
        reset = prop_u32(pnode, "qcom,mdss-dsi-reset-sequence")
        for m in modes:
            if m["off"] != modes[0]["off"]:
                sys.exit(f"{cname}: off-command differs between timings, extend the generator")
            out.append(c_cmds(f"{cname}_on_{m['rate']}", m["on"]))
            out.append(c_cmds(f"{cname}_switch_{m['rate']}", m["switch"]))
        out.append(c_cmds(f"{cname}_off", modes[0]["off"]))
        out.append(f"static const struct nx669j_mode {cname}_modes[] = {{")
        for m in modes:
            out.append(
                f"\t{{ .rate = {m['rate']}, .hdisplay = {m['w']}, .hfp = {m['hfp']}, .hpw = {m['hpw']}, .hbp = {m['hbp']},"
                f" .vdisplay = {m['h']}, .vfp = {m['vfp']}, .vpw = {m['vpw']}, .vbp = {m['vbp']},"
                f"\n\t  .on_cmds = {cname}_on_{m['rate']}, .num_on_cmds = ARRAY_SIZE({cname}_on_{m['rate']}),"
                f"\n\t  .switch_cmds = {cname}_switch_{m['rate']}, .num_switch_cmds = ARRAY_SIZE({cname}_switch_{m['rate']}) }},"
            )
        out.append("};")
        d = modes[0]
        for m in modes:
            if (m["slice_h"], m["slice_w"], m["bpc"], m["bpp"], m["spp"]) != (d["slice_h"], d["slice_w"], d["bpc"], d["bpp"], d["spp"]):
                sys.exit(f"{cname}: DSC settings differ between timings, extend the generator")
        out.append(
            f"static const struct nx669j_panel_desc {cname}_desc = {{\n"
            f"\t.name = \"{cname}\",\n"
            f"\t.reset_seq = {{ {', '.join(str(x) for x in reset)} }},\n"
            f"\t.num_reset_steps = {len(reset) // 2},\n"
            f"\t.off_cmds = {cname}_off, .num_off_cmds = ARRAY_SIZE({cname}_off),\n"
            f"\t.modes = {cname}_modes, .num_modes = ARRAY_SIZE({cname}_modes),\n"
            f"\t.dsc_slice_width = {d['slice_w']}, .dsc_slice_height = {d['slice_h']},\n"
            f"\t.dsc_bpc = {d['bpc']}, .dsc_bpp = {d['bpp']}, .dsc_slice_per_pkt = {d['spp']},\n"
            f"}};\n"
        )
        variants.append(cname)
    open(dst, "w").write("\n".join(out) + "\n")
    print("wrote", dst, "variants:", ", ".join(variants))


if __name__ == "__main__":
    main()
